### ISSUE TITLE
Not able to merge the commit due to version issue

### ISSUE THREAD

**Issue by Stephen0620** [microsoft/NimbusML-Samples#19]
**Describe the bug**
I was trying to merge the commit for fixing the issue of using wrong parameter names (#15 ). However I got an ImportError while merging the branch, so I change the line of installing the python package from "pip install https://pythonpkgdeps.blob.core.windows.net/pytlc/nimbusml-0.6.0-cp36-none-win_amd64.whl" to "pip install https://pythonpkgdeps.blob.core.windows.net/pytlc/nimbusml-1.0.0-cp37-none-win_amd64.whl", but it still doesn't work. I also tried to see what version is available through the URL, but the page was not showing anything.

**Comment by ganik** [comment]
This are outdated locations for nimbusml, now one should just pip install nimbusml
